<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arrow_Ciencias</name>
   <tag></tag>
   <elementGuidId>2722ed7e-2a73-4c48-bfe5-ae4ebb6f8ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e8b0b17d-8e4f-4594-8990-aab682cf6e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>5dab3ca6-2190-402b-9fdd-14c38691080e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>0d47891f-d420-4e20-954e-07a2c844b26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>816ea700-e007-4a34-98ba-fd21b7c08dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_7_host&quot;)/div[@class=&quot;google-aiuf&quot;]/div[@class=&quot;goog-rentries&quot;]/div[@class=&quot;google-anno-skip goog-rentry&quot;]/span[2]/svg[1]</value>
      <webElementGuid>f749b4a6-7250-4fec-8a8c-66034be6ff7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>48e7c193-11b3-426d-8b63-4384a05ccf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salud'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>f40ecf1c-3c9b-4f9d-976c-df7e3e59259b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new arrivals'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>cc4d3aac-0f52-483f-ae78-5a61f3b0de73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Ruby'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>01871a4e-2597-48fd-b0d4-77e54d7c0916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
