<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_VermsFooter2</name>
   <tag></tag>
   <elementGuidId>c304b194-02d1-4bf7-8b33-b0ba31bbc5fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aswift_1_host > div.google-aiuf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aswift_1_host']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>614c1a81-083a-442f-9c01-1de906892efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-ad-efd</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>470f29f1-b785-4d0d-8f11-e180157861a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-aiuf</value>
      <webElementGuid>1c8f8644-0782-496d-9171-aaf5859506d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver másCienciasSalud</value>
      <webElementGuid>04ac66f2-ad8b-45be-a5fd-e423eb806ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_1_host&quot;)/div[@class=&quot;google-aiuf&quot;]</value>
      <webElementGuid>5d9b8629-73ad-4f06-9b48-6c3b08ec456a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_1_host']/div</value>
      <webElementGuid>31465c16-a52a-4061-a6d8-f6d20976304e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias'])[2]/following::div[6]</value>
      <webElementGuid>4e4237ab-a470-4701-9f12-c41e34c7013c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salud'])[2]/following::div[7]</value>
      <webElementGuid>10730094-5107-41f4-bfe1-567e5c250058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p/ins/div/div</value>
      <webElementGuid>1e118bad-a64f-47b8-bdd1-25ee798a3be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ver másCienciasSalud' or . = 'Ver másCienciasSalud')]</value>
      <webElementGuid>699125f7-11ec-4afc-b5c3-a1ea1416b446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
