<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_VermsFooter3</name>
   <tag></tag>
   <elementGuidId>7ec03b22-e4e2-4f06-9fd7-a1bc0a208e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aswift_3_host > div.google-aiuf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aswift_3_host']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6878196b-83c1-4d7c-842c-fa920512bff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-ad-efd</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2240ecc7-3a66-4191-8741-05d2d4d437a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-aiuf</value>
      <webElementGuid>b9c4a6ef-48a2-4612-a249-4e87a6b5a5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver másSaludCiencias</value>
      <webElementGuid>510ad13b-2a2f-4023-a3db-38530fda1c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_3_host&quot;)/div[@class=&quot;google-aiuf&quot;]</value>
      <webElementGuid>fdf27562-fc6a-411d-a99e-4529bfac0ae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_3_host']/div</value>
      <webElementGuid>3bc33dbc-6d5d-4f19-a67d-34fffe20a374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias'])[4]/following::div[6]</value>
      <webElementGuid>8790b1a3-ed2d-43eb-9eb3-6fdcb0f072bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salud'])[4]/following::div[7]</value>
      <webElementGuid>744c9db9-1bec-4a69-a3f5-f0bbc56ba571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/p/ins/div/div</value>
      <webElementGuid>5369527e-10e3-4d2a-9bc1-a6e38f261e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ver másSaludCiencias' or . = 'Ver másSaludCiencias')]</value>
      <webElementGuid>93ea2a72-4bac-4fea-8b78-d5617687cbe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
