<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_VermsFooter1</name>
   <tag></tag>
   <elementGuidId>7bb2b6a9-8063-4a4a-bace-39ef7d66f423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aswift_0_host > div.google-aiuf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aswift_0_host']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>440aced4-2dcf-429e-8471-3257477032b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-ad-efd</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>624e46a4-1ba5-44bb-a39a-08ef0e62829e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-aiuf</value>
      <webElementGuid>57b22936-bdd1-4572-81b9-be8e0b9d1ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver másSaludCiencias</value>
      <webElementGuid>1e547007-623a-48d2-94be-53c60a776f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_0_host&quot;)/div[@class=&quot;google-aiuf&quot;]</value>
      <webElementGuid>9293561c-155f-499a-b7e0-469dd7bce862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_0_host']/div</value>
      <webElementGuid>8d168680-47cd-46ac-95f9-4106ac3eacd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to basket'])[3]/following::div[12]</value>
      <webElementGuid>c82e52f9-3ec5-42a1-9237-07b8a2ee4156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[4]/following::div[12]</value>
      <webElementGuid>478e0e63-f290-41b4-84d5-7fc417f30d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/ins/div/div</value>
      <webElementGuid>7590ee1f-178f-491c-8687-331c7fd3c58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ver másSaludCiencias' or . = 'Ver másSaludCiencias')]</value>
      <webElementGuid>7eb05cb6-4f32-4698-b8a8-e70edc605bdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
