<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_VermasSaludCiencias</name>
   <tag></tag>
   <elementGuidId>a341b5d6-7912-45a5-a21a-63941de1a328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aswift_2_host > div.google-aiuf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aswift_2_host']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>178184f3-4fde-47e2-8083-8d481086b7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-ad-efd</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b2deb59-3c5a-4965-93a5-a9f3369770d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-aiuf</value>
      <webElementGuid>0e78533d-d2fe-4f0b-bd24-b564cbad926f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver másSaludCiencias</value>
      <webElementGuid>623ed97c-f220-4bf7-a079-73ef02615cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_2_host&quot;)/div[@class=&quot;google-aiuf&quot;]</value>
      <webElementGuid>f7969469-d44b-4587-9329-7f86347189d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_2_host']/div</value>
      <webElementGuid>013e39f5-ce8c-4c2a-a2b0-28b06f79aa27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salud'])[3]/following::div[6]</value>
      <webElementGuid>09bc65c2-e477-43d9-9b92-6e34f2120110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias'])[3]/following::div[7]</value>
      <webElementGuid>bf9073dc-4a0b-446c-bd34-37984474f03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/p/ins/div/div</value>
      <webElementGuid>b3398703-d088-4da9-bf7e-43d6e2a573e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ver másSaludCiencias' or . = 'Ver másSaludCiencias')]</value>
      <webElementGuid>24c3db2d-5423-4bc1-9d1f-0de6b1ba1c50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
