<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ShopSeleniumBooks</name>
   <tag></tag>
   <elementGuidId>5b80aca4-01f4-4f2a-aaff-dd883b76a79a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-22-0-0-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text-22-0-0-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a64258fd-caa6-4475-9bc8-d7b19b6d04fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-22-0-0-1</value>
      <webElementGuid>50796e81-4a49-4720-aa47-e29a51c10a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>module module-text text-22-0-0-1   </value>
      <webElementGuid>8005740b-9dfc-43e0-9d84-b0c8d3f63497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-22-0-0-1&quot;)</value>
      <webElementGuid>49051d94-1903-4229-8728-190cae354dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='text-22-0-0-1']</value>
      <webElementGuid>166cca3f-84bf-4b15-b24b-b9be8e2150b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='themify_builder_content-22']/div/div/div/div/div/div</value>
      <webElementGuid>235e4597-cfb9-4d0d-8570-596a8dbf3a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹0.00'])[1]/following::div[34]</value>
      <webElementGuid>193a6d75-4fe4-4765-a2c8-e469dea38fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site'])[1]/following::div[34]</value>
      <webElementGuid>25357de6-0000-4cd4-928e-9f53d0c0ea01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver más'])[1]/preceding::div[21]</value>
      <webElementGuid>b8899bd8-9185-4e6e-8f3e-0bfdef09cae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salud'])[1]/preceding::div[22]</value>
      <webElementGuid>ac9af2bb-688e-4bbf-89c6-710612070810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>e952a8f6-ae00-4a3d-936d-f0bff33f1776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'text-22-0-0-1']</value>
      <webElementGuid>1bc74b22-2c60-40ce-b746-32e388162279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
