<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ThinkinginHTML</name>
   <tag></tag>
   <elementGuidId>95aa8c79-ac82-43f2-be56-301474a33af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.post-163.product.type-product.status-publish.has-post-thumbnail.product_cat-html.product_tag-html.has-post-title.no-post-date.has-post-category.has-post-tag.has-post-comment.has-post-author.first.instock.sale.downloadable.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link > img.attachment-shop_catalog.size-shop_catalog.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text-22-sub_row_1-0-2-1-0']/div/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a48a636b-b305-4d59-8937-a1c3b09f155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d79e410f-346e-4d34-abe3-33b6259afeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>99411280-70e9-45de-b0a3-146c8d970287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-300x300.jpg</value>
      <webElementGuid>1eab8892-35bc-499d-b63a-84beadb18964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_catalog size-shop_catalog wp-post-image</value>
      <webElementGuid>11aadf22-b5a0-4558-99f5-08632d50a110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Thinking in HTML</value>
      <webElementGuid>deb4d45e-3424-422f-8f5e-3a94cb72c111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>dc7047a2-6845-4c1e-8768-cafce650f4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>1a7fc931-1c60-44f0-b1a1-b44c914608ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thinking in HTML</value>
      <webElementGuid>2346a771-4650-4db7-b216-ad1776e19792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-300x300.jpg 300w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-600x600.jpg 600w</value>
      <webElementGuid>81cdfa92-e0d7-4321-9362-83d363ae9a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>6e6beaca-82cc-4845-986a-0504c3036dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-22-sub_row_1-0-2-1-0&quot;)/div[@class=&quot;woocommerce&quot;]/ul[@class=&quot;products&quot;]/li[@class=&quot;post-163 product type-product status-publish has-post-thumbnail product_cat-html product_tag-html has-post-title no-post-date has-post-category has-post-tag has-post-comment has-post-author first instock sale downloadable taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link&quot;]/img[@class=&quot;attachment-shop_catalog size-shop_catalog wp-post-image&quot;]</value>
      <webElementGuid>68b0fcfa-b577-461e-95a8-eb03e923296e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text-22-sub_row_1-0-2-1-0']/div/ul/li/a/img</value>
      <webElementGuid>f544c6a8-bd55-4148-9030-3a115c020dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Thinking in HTML']</value>
      <webElementGuid>fa85c1cc-3f04-4634-ad78-f4d01c871ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a/img</value>
      <webElementGuid>efbebd2a-3448-4492-970b-16c6c8bdb97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-300x300.jpg' and @alt = 'Thinking in HTML' and @title = 'Thinking in HTML']</value>
      <webElementGuid>8da0b869-b128-4828-aad3-501a42de72e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
