<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textField_SubscribeHereEMAIL</name>
   <tag></tag>
   <elementGuidId>004314dd-4cef-45e4-9833-d004b4a8f456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;EMAIL&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='EMAIL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>373d825a-9f01-4ef9-bc88-534e1123c381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e09742f7-7591-40cd-a4e9-ccc9e7bc6bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EMAIL</value>
      <webElementGuid>e3b7a35c-6951-486f-8796-953fa73fef2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your email address</value>
      <webElementGuid>9652832b-ed73-43a8-af44-23d8ddbce520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mc4wp-form-1&quot;)/div[@class=&quot;mc4wp-form-fields&quot;]/p[1]/input[1]</value>
      <webElementGuid>ad4b7146-3b4d-47f6-8694-6027866700f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='EMAIL']</value>
      <webElementGuid>0fba2087-db1f-40d5-a2e9-35cd984e1401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mc4wp-form-1']/div/p/input</value>
      <webElementGuid>cb6dc55e-928a-4e9e-acc1-5f721d8f2da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>9a8d7143-16af-4336-aa02-9bab0a0c787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'EMAIL' and @placeholder = 'Your email address']</value>
      <webElementGuid>f18367bf-8bdf-4d41-b727-39cb3b289993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
