<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Salud</name>
   <tag></tag>
   <elementGuidId>ff5d40be-9fcc-4a2d-93f7-28ea672d3ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;Salud&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aswift_7_host']/div/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>224a0288-4974-4204-bb21-f5ae62975e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Salud</value>
      <webElementGuid>07d6201b-0406-4186-b075-fed284a6109c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salud</value>
      <webElementGuid>364ad9b3-0dcd-43bd-b36f-bd664c70c6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_7_host&quot;)/div[@class=&quot;google-aiuf&quot;]/div[@class=&quot;goog-rentries&quot;]/div[@class=&quot;google-anno-skip goog-rentry&quot;]/span[1]</value>
      <webElementGuid>e5197c26-e638-4ce6-8c89-da73ff158b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_7_host']/div/div/div[2]/span</value>
      <webElementGuid>72f78dde-1344-49a5-bd1f-1f767367c694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver más'])[1]/following::span[1]</value>
      <webElementGuid>3a53ba38-6a05-4bc7-a993-a4e76fb65293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹0.00'])[1]/following::span[2]</value>
      <webElementGuid>50fb343b-1e90-480f-85f6-ade1660b9001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias'])[1]/preceding::span[2]</value>
      <webElementGuid>aaaff142-e9fb-4ecf-9a73-fdec2a007191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new arrivals'])[1]/preceding::span[4]</value>
      <webElementGuid>2911e776-f306-4455-bcad-bc4787910586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salud']/parent::*</value>
      <webElementGuid>9c7841f0-51ed-4e5f-b3f2-3ccc805498dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>fc5792f9-19d7-4053-be94-8e69e71ed4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Salud' and (text() = 'Salud' or . = 'Salud')]</value>
      <webElementGuid>af7596e5-342d-40f1-82cb-db9b213e83f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
