<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_price500.00</name>
   <tag></tag>
   <elementGuidId>14211200-24eb-4aa2-973b-67a6eaaf0575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.woocommerce-Price-amount.amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text-22-sub_row_1-0-2-0-0']/div/ul/li/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b0b61671-7196-4555-8240-ffb4a4d86658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-Price-amount amount</value>
      <webElementGuid>2bdc9347-e251-446b-b323-51435d07903e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹500.00</value>
      <webElementGuid>8295b855-6963-422e-9495-3362473008e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-22-sub_row_1-0-2-0-0&quot;)/div[@class=&quot;woocommerce&quot;]/ul[@class=&quot;products&quot;]/li[@class=&quot;post-160 product type-product status-publish has-post-thumbnail product_cat-selenium product_tag-ruby product_tag-selenium has-post-title no-post-date has-post-category has-post-tag has-post-comment has-post-author first instock downloadable taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link&quot;]/span[@class=&quot;price&quot;]/span[@class=&quot;woocommerce-Price-amount amount&quot;]</value>
      <webElementGuid>dd4a5663-bd35-404d-84a7-990ce2a4e21b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text-22-sub_row_1-0-2-0-0']/div/ul/li/a/span/span</value>
      <webElementGuid>77c166ca-c439-4c51-a7d6-add37e698512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Ruby'])[1]/following::span[2]</value>
      <webElementGuid>eaa84872-b056-4fec-91ea-a97b071d64de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new arrivals'])[1]/following::span[2]</value>
      <webElementGuid>a14fff34-6f91-4ecd-ba40-77c35d4a6ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to basket'])[1]/preceding::span[2]</value>
      <webElementGuid>f7989e00-d2f6-4146-9a5b-a0091885fcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='500.00']/parent::*</value>
      <webElementGuid>ca403a2d-76bc-4355-907c-07844a1819e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>7dd42e02-9782-4d69-b8e7-ce8dffccc309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '₹500.00' or . = '₹500.00')]</value>
      <webElementGuid>e1f5a7a1-b568-44bb-8842-7e3714d9690e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
