<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_AutomationPracticeSite2026</name>
   <tag></tag>
   <elementGuidId>a1603871-ad53-45a4-bb41-7d9cf099c0a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.one</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer']/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0907c2c1-5d5a-4c54-a469-c5612cd823c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>one</value>
      <webElementGuid>05527611-354c-4e85-a3fa-ee9296c5a80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>© Automation Practice Site 2026</value>
      <webElementGuid>dcf64c9e-aa6a-4be0-8584-9c31e5e02700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[@class=&quot;footer-text clearfix&quot;]/div[@class=&quot;footer-text-inner&quot;]/div[@class=&quot;one&quot;]</value>
      <webElementGuid>e150aeab-7a39-49cf-a4a9-ff11a63fdaee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div[3]/div/div</value>
      <webElementGuid>12c9deb7-172f-4511-891f-0e4eba11350b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe Here'])[1]/following::div[6]</value>
      <webElementGuid>31b377e4-7b54-4f53-a922-6860b3f236b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias'])[6]/following::div[9]</value>
      <webElementGuid>8c2f34a4-4de5-4f5c-a9f6-dd2acd1698d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salud'])[7]/preceding::div[4]</value>
      <webElementGuid>5a85eb97-4f2b-49fb-8ed7-2d68de54f5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='©']/parent::*</value>
      <webElementGuid>67ccdcda-8134-44a2-a802-15701801d156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div[3]/div/div</value>
      <webElementGuid>f88d4c6b-20d8-46cd-8daa-83c2a3dd92d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '© Automation Practice Site 2026' or . = '© Automation Practice Site 2026')]</value>
      <webElementGuid>ab1a151a-72be-49d0-ab46-2741e1e3d6a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
