<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checklist_SaveMyName</name>
   <tag></tag>
   <elementGuidId>ca15f0ba-c141-4d73-bf3f-44b1c1e3ced3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-comment-cookies-consent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wp-comment-cookies-consent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa8be5a7-7189-4b00-aeda-793f96fc121e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-comment-cookies-consent</value>
      <webElementGuid>13c47135-2066-4265-8eb2-9818008e6122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wp-comment-cookies-consent</value>
      <webElementGuid>bc353a04-0622-4ae0-82bd-6546719a7dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>98597b34-93d9-42f2-8fe0-cbc18e223ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>100d7e2d-1b05-4660-8d4e-e9b8e8e00913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-comment-cookies-consent&quot;)</value>
      <webElementGuid>7438c55c-bd7c-4fdf-8476-0007c35abbe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-comment-cookies-consent']</value>
      <webElementGuid>8d8a8f35-0211-4eba-94d0-171ea5ac5ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/p[6]/input</value>
      <webElementGuid>6cf63669-8ebe-47cd-b1a5-f89e88376b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/input</value>
      <webElementGuid>9bf335c5-1b92-46c3-8e0f-962e8e358ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wp-comment-cookies-consent' and @name = 'wp-comment-cookies-consent' and @type = 'checkbox']</value>
      <webElementGuid>d7c8457b-0308-41bc-a1eb-32223d2ca85a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
