<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_DiscoverMoreDevelopmentTools</name>
   <tag></tag>
   <elementGuidId>19eaf0a5-10b5-4e00-92db-6b0ac4e97ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aswift_3_host']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.google-aiuf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>91794d59-f0c6-4477-8b6e-8bc287edb7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-ad-efd</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a9f9e429-28fa-41a4-88ca-8e3c1ac0ec18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-aiuf</value>
      <webElementGuid>de520857-3070-45c8-ac2f-be81a12b2eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Discover moreDevelopment ToolsprogrammingProgramming</value>
      <webElementGuid>ffdb188f-40e4-4311-b055-6dd747e1ae7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_3_host&quot;)/div[@class=&quot;google-aiuf&quot;]</value>
      <webElementGuid>7dce74ce-012b-49de-a8ba-3915819305e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_3_host']/div</value>
      <webElementGuid>3089750f-47ef-47bd-97a2-13def2d4d02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews (0)'])[1]/following::div[3]</value>
      <webElementGuid>a5d38f73-f5cb-4f0f-a104-97456a7cd739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::div[3]</value>
      <webElementGuid>d727d7b9-a397-4e12-9622-0ed6fe128ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins/div/div</value>
      <webElementGuid>f091f8a0-c7d0-4b70-8f55-8332460a2652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Discover moreDevelopment ToolsprogrammingProgramming' or . = 'Discover moreDevelopment ToolsprogrammingProgramming')]</value>
      <webElementGuid>4c07a17f-1866-455a-a730-61e6377bf20a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
