<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FunctionalProgrammingPoster</name>
   <tag></tag>
   <elementGuidId>a764e5c2-40fe-4ed1-9e77-6ec607d1ca22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-170']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-shop_single.size-shop_single.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6daede36-0d0b-4df9-8983-0afe586199da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>2ed5fefa-7928-439e-a175-bbb639b0f72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>e8b2e1e5-4f79-4eee-b63a-4cfc88d3bd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-600x600.jpg</value>
      <webElementGuid>cbb1841e-89ab-4013-8859-8c225dde6a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_single size-shop_single wp-post-image</value>
      <webElementGuid>0cb5feef-3eb2-42b4-aacb-00b8d08a4001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Functional Programming in JS</value>
      <webElementGuid>a9de0881-6223-4831-ac88-d8d64fc8f779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>5d71e264-f75f-48ca-9e01-9f1bbd6e687c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Functional Programming in JS</value>
      <webElementGuid>811ee952-c2db-4188-b829-4ad164b583a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-600x600.jpg 600w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-300x300.jpg 300w</value>
      <webElementGuid>dbba1810-b4a8-468d-9ee6-79f814674dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 600px) 100vw, 600px</value>
      <webElementGuid>0e168c54-f179-4f8f-8c69-d7a901d5c365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-170&quot;)/div[@class=&quot;images&quot;]/a[@class=&quot;woocommerce-main-image zoom&quot;]/img[@class=&quot;attachment-shop_single size-shop_single wp-post-image&quot;]</value>
      <webElementGuid>9e5c1fd0-8506-4c78-9970-6988e2c5d65d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-170']/div/a/img</value>
      <webElementGuid>c40d6b2e-35cc-4cec-99ec-141b9159e237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Functional Programming in JS']</value>
      <webElementGuid>a862a3a5-0709-454d-8e29-573fa7c85176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>b6772028-e112-4e92-9eb9-8fceba21b0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-600x600.jpg' and @alt = 'Functional Programming in JS' and @title = 'Functional Programming in JS']</value>
      <webElementGuid>b228fbfd-1c45-46b6-8cf7-62fedbeeabff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
