<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_JSDataStructurePoster</name>
   <tag></tag>
   <elementGuidId>47e2c0e2-5c30-4379-bf66-94a19cc843bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-180']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-shop_single.size-shop_single.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0b168800-d107-4b95-9372-62383aa8e548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>28d6dced-070b-447e-9350-243d3d9b9486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>272971d2-8625-4136-9e51-2d9c8d569059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-600x600.jpg</value>
      <webElementGuid>51b2f152-dd6f-4730-9b5d-46fc5a6979d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_single size-shop_single wp-post-image</value>
      <webElementGuid>23c9f536-e2d5-46fc-b545-71805b0987ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Learning JavaScript Data Structures and Algorith</value>
      <webElementGuid>7cca359c-52cc-402a-9c11-5db88dc11c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6698b979-f3f1-4c3d-bdcc-df4c21d3595f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Learning JavaScript Data Structures and Algorith</value>
      <webElementGuid>d2fe672a-62cc-41ee-8b65-787f98c4b6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-600x600.jpg 600w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-300x300.jpg 300w</value>
      <webElementGuid>f9cd1d14-7565-4cfd-9a44-4cd5011362f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 600px) 100vw, 600px</value>
      <webElementGuid>a63a8816-6de8-4e32-88d6-3daaa462499e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-180&quot;)/div[@class=&quot;images&quot;]/a[@class=&quot;woocommerce-main-image zoom&quot;]/img[@class=&quot;attachment-shop_single size-shop_single wp-post-image&quot;]</value>
      <webElementGuid>10f05a4e-092f-4446-a2d8-aa500658de8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-180']/div/a/img</value>
      <webElementGuid>33f0bdc4-981e-4546-98e3-d3b7544e46b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Learning JavaScript Data Structures and Algorith']</value>
      <webElementGuid>d9f5cb55-4574-40ba-9768-dd891c0a8c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>7c8c4707-0e44-49f1-9a02-6e4672b61815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-600x600.jpg' and @alt = 'Learning JavaScript Data Structures and Algorith' and @title = 'Learning JavaScript Data Structures and Algorith']</value>
      <webElementGuid>6d011792-04b6-4825-8e88-8a41a3700cdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
