<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MasteringJavaScriptPoster</name>
   <tag></tag>
   <elementGuidId>b2d15184-1c3f-4d4f-bb6e-863285567a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-165']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-shop_single.size-shop_single.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>54f4a402-7572-4df9-ac61-c27300221a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>311ea913-bec9-4dd7-8c21-eebf8446ef9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>731251e6-fc72-4953-b6ca-039620630ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-JavaScript-600x600.jpg</value>
      <webElementGuid>7c032a4c-d65f-4b6b-bd9d-20e4dd48a5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_single size-shop_single wp-post-image</value>
      <webElementGuid>3aaf9551-de5b-4c57-8251-84d377af5e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mastering JavaScript</value>
      <webElementGuid>746c0433-803b-47b8-a40a-e9f30d1d7b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>7ef4a122-e901-4d88-9657-aa1797c04f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mastering JavaScript</value>
      <webElementGuid>5469a110-bf11-49d4-9104-f56721ce674d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-JavaScript-600x600.jpg 600w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-JavaScript-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-JavaScript-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-JavaScript-300x300.jpg 300w</value>
      <webElementGuid>a5959c8b-24e0-40fc-8b69-a456aff401a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 600px) 100vw, 600px</value>
      <webElementGuid>416f98bf-bb18-47e8-85a3-3f267f627ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-165&quot;)/div[@class=&quot;images&quot;]/a[@class=&quot;woocommerce-main-image zoom&quot;]/img[@class=&quot;attachment-shop_single size-shop_single wp-post-image&quot;]</value>
      <webElementGuid>cf61c5fd-5b4e-416e-b51c-7961ac91cfa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-165']/div/a/img</value>
      <webElementGuid>c66f2b88-a644-4123-a331-229088ba1980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mastering JavaScript']</value>
      <webElementGuid>43336f55-f233-459a-9cf4-108a4ef3cf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>53ec992c-0b01-432a-b83f-cd2096e99f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-JavaScript-600x600.jpg' and @alt = 'Mastering JavaScript' and @title = 'Mastering JavaScript']</value>
      <webElementGuid>28eb32cc-e64a-4ec6-adfd-2de3d0fcfe24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
