<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_HTML5WebbAppDevelopment</name>
   <tag></tag>
   <elementGuidId>741c27a5-51f0-490e-ab1b-cb112ac5d995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-182']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-shop_single.size-shop_single.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>59e6a3d1-8eaa-405d-b772-bcecb66829a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>b0b225f6-253c-4f28-8e09-c9e9fef668be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>ba66bdd8-2324-4eae-9046-0d7c52f4ef4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/HTML5-Web-Application-Development-Beginners-guide-600x600.jpg</value>
      <webElementGuid>f1129f85-6f76-4d53-83d6-e45e62db19ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_single size-shop_single wp-post-image</value>
      <webElementGuid>38062b12-df29-47cf-afdd-876f0d9cf494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>HTML5 Web Application Development Beginner's guide</value>
      <webElementGuid>c49d0021-8c66-4cf5-9b4c-bd9b66c893d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>93d2c8b0-208c-4d4c-ba39-55d2d4331feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML5 Web Application Development Beginner's guide</value>
      <webElementGuid>d6d62f07-b9b8-41d6-86a1-d6950dde62f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/HTML5-Web-Application-Development-Beginners-guide-600x600.jpg 600w, https://practice.automationtesting.in/wp-content/uploads/2017/01/HTML5-Web-Application-Development-Beginners-guide-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/HTML5-Web-Application-Development-Beginners-guide-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/HTML5-Web-Application-Development-Beginners-guide-300x300.jpg 300w</value>
      <webElementGuid>ad6708f9-501c-4947-a62d-3aa4505ba710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 600px) 100vw, 600px</value>
      <webElementGuid>cb99f108-2495-4217-a925-cdb2e6035dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-182&quot;)/div[@class=&quot;images&quot;]/a[@class=&quot;woocommerce-main-image zoom&quot;]/img[@class=&quot;attachment-shop_single size-shop_single wp-post-image&quot;]</value>
      <webElementGuid>fe2a4da9-a0a9-4b91-8114-c179ad1d5bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-182']/div/a/img</value>
      <webElementGuid>7f056ce3-4abf-4c11-872f-126936c9aa13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;HTML5 Web Application Development Beginner's guide&quot;]</value>
      <webElementGuid>658b1e86-aa95-49c3-b431-6143233ec4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>b9286f57-08d9-41bb-8453-855e64826a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/HTML5-Web-Application-Development-Beginners-guide-600x600.jpg' and @alt = concat(&quot;HTML5 Web Application Development Beginner&quot; , &quot;'&quot; , &quot;s guide&quot;) and @title = concat(&quot;HTML5 Web Application Development Beginner&quot; , &quot;'&quot; , &quot;s guide&quot;)]</value>
      <webElementGuid>f305917e-8ea5-42ed-88f1-c455f6cb0d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
