<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MasteringHTML5Poster</name>
   <tag></tag>
   <elementGuidId>94bc70f0-27c2-4957-8552-c2a08905b05c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-181']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-shop_single.size-shop_single.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5782033-d95b-4f79-8ab9-b8c1544edc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>2b94018c-bd33-4bc9-9665-65576944335b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>1614f13f-d755-45d5-b0c9-06b648430e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-600x600.jpg</value>
      <webElementGuid>22af3edc-6e80-498f-8be1-cd1d08072eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_single size-shop_single wp-post-image</value>
      <webElementGuid>91801a2a-0336-457a-ab41-b3d262e41910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mastering HTML5 Forms</value>
      <webElementGuid>9a6c8772-49f5-4f6a-b123-43e16b452cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8f8cb08f-d464-42f4-85bc-5d28540f0e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mastering HTML5 Forms</value>
      <webElementGuid>119ca8bb-aad3-4de5-b640-5aa25e272e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-600x600.jpg 600w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-300x300.jpg 300w</value>
      <webElementGuid>3a6568c6-a4b0-4e5c-a3c3-8d91ba43c02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 600px) 100vw, 600px</value>
      <webElementGuid>bf8ecb25-87a8-45e6-813d-123c7cee5e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-181&quot;)/div[@class=&quot;images&quot;]/a[@class=&quot;woocommerce-main-image zoom&quot;]/img[@class=&quot;attachment-shop_single size-shop_single wp-post-image&quot;]</value>
      <webElementGuid>5157aced-297a-432f-9fe9-f5dd964b806a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-181']/div/a/img</value>
      <webElementGuid>a30c5f3e-2541-4a77-809b-1a1dd33aec11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mastering HTML5 Forms']</value>
      <webElementGuid>33d81a1d-8e68-46c2-a21f-cea83a4274a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>ff46d688-9e3c-422f-a31d-8e9b3241027b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-600x600.jpg' and @alt = 'Mastering HTML5 Forms' and @title = 'Mastering HTML5 Forms']</value>
      <webElementGuid>533980b5-8a27-4dc0-9148-3ea6e11083cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
