<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_HomeThinkingInHTML</name>
   <tag></tag>
   <elementGuidId>b359585b-d7fb-4671-8985-f0f2b3f76c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/nav</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.woocommerce-breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>47c8844a-37b7-44ae-a7da-7e0592125d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-breadcrumb</value>
      <webElementGuid>81166bea-c7a4-4c38-ae0a-95e43e969179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>breadcrumb</value>
      <webElementGuid>347dcb46-9dc1-4bf8-9141-c41db393a163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home / HTML / Thinking in HTML</value>
      <webElementGuid>dec4eab3-51ac-4569-bf8e-79931474bccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/nav[@class=&quot;woocommerce-breadcrumb&quot;]</value>
      <webElementGuid>0a6a1625-0102-4bb7-993e-97e8f7f0644a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/nav</value>
      <webElementGuid>e880495c-9be0-4197-ada3-3b6a0abf49d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1,580.00'])[1]/following::nav[1]</value>
      <webElementGuid>06f74c1a-3501-44ac-88b3-80774e5ade9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site'])[1]/following::nav[1]</value>
      <webElementGuid>861d8296-b09b-492d-89a3-e5d6c18a645e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav</value>
      <webElementGuid>53dcb301-6edd-4303-8a28-97bcc11e69c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Home / HTML / Thinking in HTML' or . = 'Home / HTML / Thinking in HTML')]</value>
      <webElementGuid>9eae68d2-e200-48e7-972f-14274a5f113b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
