<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_HomeMasteringJavaScript</name>
   <tag></tag>
   <elementGuidId>6b74a521-b22f-43e2-9c01-ad545d5a0d08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/nav</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.woocommerce-breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>0d50b25f-95cf-46e3-aecc-7b405e0bbcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-breadcrumb</value>
      <webElementGuid>79917fab-ff3d-4944-b022-4532d662a8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>breadcrumb</value>
      <webElementGuid>4b82cefb-709e-4c15-8854-1f26e5d7dcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home / JavaScript / Mastering JavaScript</value>
      <webElementGuid>471631ea-a099-49d6-9559-70de02fcf8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/nav[@class=&quot;woocommerce-breadcrumb&quot;]</value>
      <webElementGuid>351ad11f-3f59-4a03-9ae8-aeeda4abfa82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/nav</value>
      <webElementGuid>0f76f8ac-7098-4197-8f25-de0cc01bb18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹450.00'])[1]/following::nav[1]</value>
      <webElementGuid>fdeb496d-f8b5-47e8-9ef5-dd88729f67b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site'])[1]/following::nav[1]</value>
      <webElementGuid>60bb1a21-92a6-4e56-9f54-fdd957d521e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav</value>
      <webElementGuid>924a25ba-5b62-4d9d-82a8-6e305a5faef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Home / JavaScript / Mastering JavaScript' or . = 'Home / JavaScript / Mastering JavaScript')]</value>
      <webElementGuid>ac20774e-c7dd-46ed-b13d-1629ca1b5add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
