<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>price_400.00</name>
   <tag></tag>
   <elementGuidId>126dedff-e2c7-4cdd-be41-ea6829111684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-163']/div[2]/div/p/ins/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ins > span.woocommerce-Price-amount.amount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7617b2d0-d841-4b62-b16e-a9f63a74f57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-Price-amount amount</value>
      <webElementGuid>351df719-022f-4fae-8ea9-a074428e0437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹400.00</value>
      <webElementGuid>185edb93-7685-4026-ab66-fdb63e5ad580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-163&quot;)/div[@class=&quot;summary entry-summary&quot;]/div[1]/p[@class=&quot;price&quot;]/ins[1]/span[@class=&quot;woocommerce-Price-amount amount&quot;]</value>
      <webElementGuid>2c52f58e-a30f-44c3-9e53-d5344dd47ce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-163']/div[2]/div/p/ins/span</value>
      <webElementGuid>25ece9f6-f16c-465b-9ce7-2ebc65e1bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[1]/following::span[1]</value>
      <webElementGuid>61a92fbc-bfa3-4604-8ef4-9ef613959e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thinking in HTML'])[1]/following::span[3]</value>
      <webElementGuid>499f2183-53ac-43ce-ad4e-2d2f3cd38bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Word Processing Software'])[1]/preceding::span[3]</value>
      <webElementGuid>292fbf58-4dac-4f9b-bc2a-e7d53539b2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='400.00']/parent::*</value>
      <webElementGuid>5dd60672-9d73-4de0-b729-abca5c296667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins/span</value>
      <webElementGuid>b85124e7-d482-419e-8801-ab8162eaf22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '₹400.00' or . = '₹400.00')]</value>
      <webElementGuid>66eabeb4-c7cd-4551-9db3-d18071c008a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
