<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Description</name>
   <tag></tag>
   <elementGuidId>949d1fa0-2759-488e-997b-a87848a048e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-160']/div[3]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.description_tab.active > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb8bd786-36aa-4a8a-8187-0e8583f218de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-description</value>
      <webElementGuid>d4a0782a-2e34-4f04-b582-a5d688ffe4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>304177ee-5a65-4152-b893-54236b67a799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-160&quot;)/div[@class=&quot;woocommerce-tabs wc-tabs-wrapper&quot;]/ul[@class=&quot;tabs wc-tabs&quot;]/li[@class=&quot;description_tab active&quot;]/a[1]</value>
      <webElementGuid>b3b83b82-da73-47fb-9290-c26ceeb1ded4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-160']/div[3]/ul/li/a</value>
      <webElementGuid>4e968b53-7a25-4b40-8b4e-de2ae4f3e06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Description')]</value>
      <webElementGuid>3a7c068a-feb5-4559-be77-33894dc6e686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selenium'])[3]/following::a[1]</value>
      <webElementGuid>a4a3679c-57b1-40ed-b31c-1c794fdcbfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ruby'])[1]/following::a[2]</value>
      <webElementGuid>4b53084a-3842-4932-96cc-e5da3829e02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews (0)'])[1]/preceding::a[1]</value>
      <webElementGuid>518d2e55-c111-424c-9934-72016907cfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Description'])[1]/preceding::a[2]</value>
      <webElementGuid>c5d1a808-45ea-4683-8213-facdac2ac2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Description']/parent::*</value>
      <webElementGuid>60fc7847-d439-4ec2-918e-daddd4eca4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-description')]</value>
      <webElementGuid>738d25d7-5bd2-4b31-ace1-9df76795b37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a</value>
      <webElementGuid>52aeaf0f-5477-4d5c-b8e3-ffb42ea7f383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-description' and (text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>4efcb654-a3de-4347-b2bb-00dd10f763b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
