<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_BeTheFirstToReviewMasteringJavaScript</name>
   <tag></tag>
   <elementGuidId>cf2d0f6b-b234-49ee-9825-1c5e6fbec41c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='reply-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reply-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>2dfba1a9-e5ed-4642-af37-30835575ab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply-title</value>
      <webElementGuid>4eb51f20-e534-469c-a9c3-7c22fe061c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-reply-title</value>
      <webElementGuid>a916d891-4cea-4171-a637-10784015a21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Be the first to review “Mastering JavaScript” Cancel reply</value>
      <webElementGuid>4c4ce56b-6249-4dfd-a47b-58aee08f563c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply-title&quot;)</value>
      <webElementGuid>dd93a7f9-1b70-4832-bd62-8c21916bbabf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='reply-title']</value>
      <webElementGuid>0d32a5b6-2f58-4392-8ca2-146cf9332e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='respond']/h3</value>
      <webElementGuid>b1f3abb6-e4b4-41c5-89a2-5d1aac22b51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::h3[1]</value>
      <webElementGuid>7ee9edee-d444-4ac1-84aa-a7db9bd3362c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java (Programming Language)'])[2]/following::h3[1]</value>
      <webElementGuid>8e2f6c6d-ab8d-4e98-bc41-d4cb26a59308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email address will not be published.'])[1]/preceding::h3[1]</value>
      <webElementGuid>9630c808-3283-4e02-ac7e-13b7c308939f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Be the first to review “Mastering JavaScript”']/parent::*</value>
      <webElementGuid>c0a23d59-f5ef-4755-abda-e271fc9b4323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>dbab1280-e086-4f25-bf6d-48b07ae7d5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'reply-title' and (text() = 'Be the first to review “Mastering JavaScript” Cancel reply' or . = 'Be the first to review “Mastering JavaScript” Cancel reply')]</value>
      <webElementGuid>765c1ef7-4391-4574-aa42-50b7bf248daf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
