<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_BeTheFirstToReviewThinkingInHTML</name>
   <tag></tag>
   <elementGuidId>7eaafa3c-e626-45de-a29b-2805be7aaac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='reply-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reply-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>62465fe9-a503-49e8-813c-6265891feed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply-title</value>
      <webElementGuid>de98f798-6a43-4111-a658-111c02e0c63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-reply-title</value>
      <webElementGuid>dee1a3ce-0498-47e4-af6a-e1f245d5cd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Be the first to review “Thinking in HTML” Cancel reply</value>
      <webElementGuid>d06e3473-5212-4209-8cee-bd9d633c88ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply-title&quot;)</value>
      <webElementGuid>2fe03533-b536-4ee6-8b14-d5de59fb9ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='reply-title']</value>
      <webElementGuid>7e6936bc-ca69-4d0a-874b-e8c9cde52b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='respond']/h3</value>
      <webElementGuid>b2b3fe23-c88f-4642-ae86-f071eb60cdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::h3[1]</value>
      <webElementGuid>20ff3e78-2a8c-43ff-873b-c9142703de33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Description'])[1]/following::h3[1]</value>
      <webElementGuid>710d3e52-1b7c-485e-a40b-5683e4d8f277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email address will not be published.'])[1]/preceding::h3[1]</value>
      <webElementGuid>58aef586-88e2-4d42-9875-2e401fec774d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Be the first to review “Thinking in HTML”']/parent::*</value>
      <webElementGuid>d288a415-bd57-49ad-a859-dae718612f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>726e5a38-2c64-4b6f-9566-3f0c7c578390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'reply-title' and (text() = 'Be the first to review “Thinking in HTML” Cancel reply' or . = 'Be the first to review “Thinking in HTML” Cancel reply')]</value>
      <webElementGuid>90c5ecd6-80fe-4cc5-a9e4-c7391eb21004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
