<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_BeTheFirstToReviewSelenium Ruby</name>
   <tag></tag>
   <elementGuidId>403265a9-3887-4a9f-a369-73970c3ec963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='reply-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reply-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0c541ac9-a0fd-4912-b2e2-5c5cbe8c9a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply-title</value>
      <webElementGuid>a6bc9454-0ef3-4638-9678-91bb723a2905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-reply-title</value>
      <webElementGuid>c55f45cf-afb5-4087-9ebc-a999b4a09e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Be the first to review “Selenium Ruby” Cancel reply</value>
      <webElementGuid>c4d23c7d-38f5-41f9-bbd8-6e61269253bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply-title&quot;)</value>
      <webElementGuid>74cf4c5d-c11f-4cf2-9cf9-129bb01db12e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='reply-title']</value>
      <webElementGuid>bb26c8b1-2157-4c35-9389-77d4bc5f640d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='respond']/h3</value>
      <webElementGuid>5c811e3f-bd7f-4244-9c7b-d7bfb67dfca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::h3[1]</value>
      <webElementGuid>69621e0a-11a6-4a5f-800e-74a8b2db2409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Description'])[1]/following::h3[1]</value>
      <webElementGuid>753993e8-6a6b-45d0-89f7-3778b53d48a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email address will not be published.'])[1]/preceding::h3[1]</value>
      <webElementGuid>b0dc4942-e213-462f-8dbc-033272d67b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Be the first to review “Selenium Ruby”']/parent::*</value>
      <webElementGuid>61b8dc55-6d4a-4a18-bc25-5b8fdfec243a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>2e265353-9759-4af2-8e17-d6bd53fc1484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'reply-title' and (text() = 'Be the first to review “Selenium Ruby” Cancel reply' or . = 'Be the first to review “Selenium Ruby” Cancel reply')]</value>
      <webElementGuid>f566048a-e679-49f9-9f04-50ba6c05651b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
