<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_TagsJavascript,Mastering</name>
   <tag></tag>
   <elementGuidId>fd6e4ac6-ce0d-49d6-9fd2-e88e91ef5719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-165']/div[2]/div[3]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.tagged_as</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0818357a-2695-4701-a8e0-9c7fa7beeb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tagged_as</value>
      <webElementGuid>4ff731c2-58bb-4c7a-b158-1735d86ae05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tags: javascript, mastering</value>
      <webElementGuid>344d1661-0a74-48c5-abeb-20ab3f027ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-165&quot;)/div[@class=&quot;summary entry-summary&quot;]/div[@class=&quot;product_meta&quot;]/span[@class=&quot;tagged_as&quot;]</value>
      <webElementGuid>39d91e26-c8d9-4144-859f-adaaf923b191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-165']/div[2]/div[3]/span[2]</value>
      <webElementGuid>45191b5b-30fb-45a9-9927-bbb87d102c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[2]/following::span[1]</value>
      <webElementGuid>9428e7ad-2ad9-454f-b934-cccfd488414c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tags:']/parent::*</value>
      <webElementGuid>bc0fc379-1bc7-40b8-a6f8-c68b0d7ee3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>a2e97d86-11d9-46ac-9dbf-bc26e2b8bd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tags: javascript, mastering' or . = 'Tags: javascript, mastering')]</value>
      <webElementGuid>81b06d5f-3b8d-4f48-a50b-cffcfa3759d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
