<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_BeTheFirstToReviewHTML5</name>
   <tag></tag>
   <elementGuidId>501dc7a2-dde3-481c-bfd4-82255fa0acf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='reply-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reply-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>e4e79c10-e08a-4ac0-be5d-262d0f3ebc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply-title</value>
      <webElementGuid>df6607d7-8326-489a-98e4-f2ef9f336403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-reply-title</value>
      <webElementGuid>7b55923d-c3bc-48d0-8427-cc7768537c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Be the first to review “HTML5 Forms” Cancel reply</value>
      <webElementGuid>cc559046-5058-4ded-b178-a1ae3423a59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply-title&quot;)</value>
      <webElementGuid>97fbb811-05df-4b4d-9ba0-db03d3cec0a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='reply-title']</value>
      <webElementGuid>93c6b3db-9b30-4c47-bccb-3bd8cf869bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='respond']/h3</value>
      <webElementGuid>8ec28afb-6c03-48f5-b420-c039720be826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::h3[1]</value>
      <webElementGuid>1988ffc6-5740-44b1-9e56-c60f0e0d7cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software'])[2]/following::h3[1]</value>
      <webElementGuid>9f148912-bf00-44ed-bbd6-5a944e201525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email address will not be published.'])[1]/preceding::h3[1]</value>
      <webElementGuid>fd243a9a-7d15-4968-8b7b-cd9832f49a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Be the first to review “HTML5 Forms”']/parent::*</value>
      <webElementGuid>87e14578-4099-4542-a0b7-149e64e69d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>91dc269d-cc9b-48f9-921a-ab8b58b7708a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'reply-title' and (text() = 'Be the first to review “HTML5 Forms” Cancel reply' or . = 'Be the first to review “HTML5 Forms” Cancel reply')]</value>
      <webElementGuid>28b63f29-80d4-4f63-8095-f87cfb76741a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
