<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_BeTheFirstToReviewFunctionalProgramming</name>
   <tag></tag>
   <elementGuidId>0e1f0c3b-17d9-4b75-82ee-1007a0c50cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='reply-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reply-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>52d9ff1a-c4da-4baf-856a-571710833725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply-title</value>
      <webElementGuid>4fb0a19f-1d36-4089-80cd-89b32f06f897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-reply-title</value>
      <webElementGuid>f072794b-c420-4919-9c7e-6c6d1494ffe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Be the first to review “Functional Programming in JS” Cancel reply</value>
      <webElementGuid>b8116c30-bfee-403c-8978-3ba5dae18dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply-title&quot;)</value>
      <webElementGuid>6202296d-1126-4da9-b916-6131f4d0ca86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='reply-title']</value>
      <webElementGuid>187ac2ca-39ab-4d3e-8329-a4d95b789ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='respond']/h3</value>
      <webElementGuid>09595adf-3bc7-4054-8e90-503d5f442cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::h3[1]</value>
      <webElementGuid>898f58b2-1425-4656-bfac-c5d3f7dc7ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programming'])[3]/following::h3[1]</value>
      <webElementGuid>ecf09aba-1d61-4d47-b9fe-f198748007d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email address will not be published.'])[1]/preceding::h3[1]</value>
      <webElementGuid>955968a6-290e-4ac7-82ca-9ddc114cf02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Be the first to review “Functional Programming in JS”']/parent::*</value>
      <webElementGuid>3831ecf1-6dc9-4849-a816-fa01cabbf53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>0af4c66f-b358-448f-b214-84568610c5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'reply-title' and (text() = 'Be the first to review “Functional Programming in JS” Cancel reply' or . = 'Be the first to review “Functional Programming in JS” Cancel reply')]</value>
      <webElementGuid>a7186c0c-927b-41a1-b693-75d9b53b984d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
