<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_CategoryJavaScript</name>
   <tag></tag>
   <elementGuidId>27563839-9722-4225-bd4f-29fc06dd877e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-170']/div[2]/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.posted_in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e8d02a2-f282-4d6f-b005-957aede88c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>posted_in</value>
      <webElementGuid>2d261535-60c5-486e-a068-90dfe5ec011f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Category: JavaScript</value>
      <webElementGuid>3cf5c623-8884-4f4e-a45d-caccaa74ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-170&quot;)/div[@class=&quot;summary entry-summary&quot;]/div[@class=&quot;product_meta&quot;]/span[@class=&quot;posted_in&quot;]</value>
      <webElementGuid>6d26f974-e0c1-4782-922a-e4ac395c6abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-170']/div[2]/div[3]/span</value>
      <webElementGuid>6de4eea5-a26a-4a54-b0f4-4a8f20c16071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to basket'])[1]/following::span[1]</value>
      <webElementGuid>f5c22dec-00b8-4516-b6a3-3ba3ce6e3e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programming'])[1]/following::span[1]</value>
      <webElementGuid>bf37ec4e-e403-41d3-9128-22b7288abc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Category:']/parent::*</value>
      <webElementGuid>5311e674-ad59-4d70-9a41-ea82a6fd9385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/span</value>
      <webElementGuid>9e8002d7-0f1b-4992-a758-fc53665e7d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Category: JavaScript' or . = 'Category: JavaScript')]</value>
      <webElementGuid>07c9e5e9-4ed8-4d19-9d15-663974150610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
