<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_YourEmailAddressWillNotBePublished</name>
   <tag></tag>
   <elementGuidId>e327c6dc-8948-4c3a-98c5-00721f1eb9b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='commentform']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.comment-notes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c967e84f-d857-4c81-8cfc-b98e3e0e1752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-notes</value>
      <webElementGuid>afdeb6f6-fec0-4f04-9b98-58967fc5cf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your email address will not be published. Required fields are marked *</value>
      <webElementGuid>cfeb514a-2779-4635-92b1-272a4b4322dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commentform&quot;)/p[@class=&quot;comment-notes&quot;]</value>
      <webElementGuid>02138169-3e91-4743-82bc-2b92513496f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/p</value>
      <webElementGuid>3e242a94-b361-4f30-8cca-f87c30fb95c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel reply'])[1]/following::p[1]</value>
      <webElementGuid>ddbdc662-ef59-4ba1-9779-e647e685e78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p</value>
      <webElementGuid>45474981-7d54-4e5a-b54f-430d3e5daa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Your email address will not be published. Required fields are marked *' or . = 'Your email address will not be published. Required fields are marked *')]</value>
      <webElementGuid>f2d28b26-55a4-40f3-8619-e584c0e01fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
