<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_TagJavascript</name>
   <tag></tag>
   <elementGuidId>b4942a4d-3446-4d50-87a7-3152e923bc94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-170']/div[2]/div[3]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.tagged_as</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16d7c4e3-d085-4e8b-90bb-b10ca694d9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tagged_as</value>
      <webElementGuid>07958396-cc2a-490b-829f-fd4379cdad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tag: javascript</value>
      <webElementGuid>cd8e4052-8c3c-4a83-a2c7-96539fd91feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-170&quot;)/div[@class=&quot;summary entry-summary&quot;]/div[@class=&quot;product_meta&quot;]/span[@class=&quot;tagged_as&quot;]</value>
      <webElementGuid>58365b07-1b9e-4f74-9a83-a9bd51f9c93b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-170']/div[2]/div[3]/span[2]</value>
      <webElementGuid>eae57a46-5062-4555-8116-98c50a66c4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[2]/following::span[1]</value>
      <webElementGuid>4d7122b7-5ecd-4480-aba3-18d4a35517dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::span[1]</value>
      <webElementGuid>2efee67c-360e-4500-8342-f7e1be87c10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tag:']/parent::*</value>
      <webElementGuid>d102782d-1e27-44bc-9aa5-3dcc8e3d9e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/span[2]</value>
      <webElementGuid>a05a885f-3e49-44b5-9f0e-234277c2a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tag: javascript' or . = 'Tag: javascript')]</value>
      <webElementGuid>30f60194-24fb-4218-9708-22c6ae683578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
