<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_ViewBasketThinkingInHTML</name>
   <tag></tag>
   <elementGuidId>49c1cc38-c290-4d91-85a4-dc0708b57383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41cc632a-4d1f-4eb9-a742-c9125333f8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-message</value>
      <webElementGuid>bc13836b-db19-42ee-87b7-ed6e255d254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Basket “Thinking in HTML” has been added to your basket.</value>
      <webElementGuid>5b58e7c0-c714-423e-965c-9ce2b480b679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;woocommerce-message&quot;]</value>
      <webElementGuid>ff096577-22ec-4eb6-9bd6-d4155ee06e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div</value>
      <webElementGuid>19186ca9-efd9-495e-8590-0aed78d56cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[1]/following::div[1]</value>
      <webElementGuid>1ddd3856-9c6b-4557-8449-d0cf07606c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[1]</value>
      <webElementGuid>7c015bc1-fd3a-4d9a-8d7a-e33c8d14d5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[1]/preceding::div[1]</value>
      <webElementGuid>defb1427-61c6-41a7-9917-6faab406836c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='“Thinking in HTML” has been added to your basket.']/parent::*</value>
      <webElementGuid>13a5e1ef-aecc-4f81-9223-3b3aa3716964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>df38ff9c-c45b-4d7d-bd1e-acf54c676061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'View Basket “Thinking in HTML” has been added to your basket.' or . = 'View Basket “Thinking in HTML” has been added to your basket.')]</value>
      <webElementGuid>593c9503-396a-4fe2-961d-e9d28abfcafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
