<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Categoryselenium</name>
   <tag></tag>
   <elementGuidId>75994f01-87a3-4f4a-a22c-8a4a7b52ac90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-160']/div[2]/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.posted_in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a3d7756-9b78-4af8-a916-3d2af72cab9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>posted_in</value>
      <webElementGuid>491dbec4-8d24-4c10-8f31-3b4882f8501c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Category: selenium</value>
      <webElementGuid>4223cbe1-a859-4850-aeae-d4b6edbe2821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-160&quot;)/div[@class=&quot;summary entry-summary&quot;]/div[@class=&quot;product_meta&quot;]/span[@class=&quot;posted_in&quot;]</value>
      <webElementGuid>87013964-4005-4219-8bf0-6b950b0fd9bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-160']/div[2]/div[3]/span</value>
      <webElementGuid>dbb1bd79-70d4-44ae-90e2-c8fee14d0967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to basket'])[1]/following::span[1]</value>
      <webElementGuid>dd25754c-68d8-4f0e-b24c-18aba1df436b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[1]/following::span[1]</value>
      <webElementGuid>1e054b1a-7528-4b8d-b919-5776eb3c2e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Category:']/parent::*</value>
      <webElementGuid>0ff38c57-be04-4732-8d88-745c1b6f229d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/span</value>
      <webElementGuid>356764ff-0db8-48ab-aed5-5792d3e6a4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Category: selenium' or . = 'Category: selenium')]</value>
      <webElementGuid>6421d8da-37d3-47e1-bb73-f04af43ebc85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
