<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_ViewBasketFunctionalProgrammingAdded</name>
   <tag></tag>
   <elementGuidId>e4292a9f-b081-483c-a5b9-c4a4a0eef332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1fa7de7-f7d3-4701-8848-3348a8d60420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-message</value>
      <webElementGuid>ed850209-fdf6-4540-b384-ebf8063f8447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Basket “Functional  Programming in JS” has been added to your basket.Programming</value>
      <webElementGuid>65ed4255-eb49-4dde-a2ee-dede31de925a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;woocommerce-message&quot;]</value>
      <webElementGuid>c9e51393-2556-4069-a24c-0618606e456d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div</value>
      <webElementGuid>e88ac0b0-6969-4d6b-a2ba-3206d9558e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[1]/following::div[1]</value>
      <webElementGuid>b42d3283-7dc1-49c7-936b-f7f745b52a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[1]</value>
      <webElementGuid>74cd2ef7-c650-4bba-b9ca-23ab0a602934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='“Functional']/parent::*</value>
      <webElementGuid>81709221-d32e-478d-a222-818e0c780d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>1b67303d-83ed-47e8-8839-6ae49ab379ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'View Basket “Functional  Programming in JS” has been added to your basket.Programming' or . = 'View Basket “Functional  Programming in JS” has been added to your basket.Programming')]</value>
      <webElementGuid>823f8e91-bf06-4f6e-b8fb-35d8576013bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
