<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilterCategory_selenium</name>
   <tag></tag>
   <elementGuidId>04c8fcc8-4a18-4b4f-b721-faf7b8be4e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-17 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='woocommerce_product_categories-2']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bffcf26e-0496-4266-8bf9-0132f0828495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product-category/selenium/</value>
      <webElementGuid>cb5f97d3-0c29-4b05-8b97-a9dea7f31352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>selenium</value>
      <webElementGuid>9f2e26f3-f5d5-40d6-a9d9-2726b6319e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;woocommerce_product_categories-2&quot;)/ul[@class=&quot;product-categories&quot;]/li[@class=&quot;cat-item cat-item-17&quot;]/a[1]</value>
      <webElementGuid>c7291fb9-0e72-4b41-81d8-e70397d93794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='woocommerce_product_categories-2']/ul/li[4]/a</value>
      <webElementGuid>360b7b33-8155-436b-8acb-da3d6e4db892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'selenium')]</value>
      <webElementGuid>a3dac866-eeb2-4f25-a236-7a5245dc0fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[2]/following::a[1]</value>
      <webElementGuid>b0d8304b-8171-467f-983e-3413d8989a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[1]/following::a[1]</value>
      <webElementGuid>19257756-4cf7-474e-afc1-d56f8d338274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[2]/preceding::a[1]</value>
      <webElementGuid>9288044e-3cec-499d-81e4-b1f55904af16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver más'])[1]/preceding::a[1]</value>
      <webElementGuid>06f25167-336c-42f4-a0c1-220586492da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='selenium']/parent::*</value>
      <webElementGuid>c70b25fb-cf68-4fea-96bf-a84ff0835d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/product-category/selenium/')]</value>
      <webElementGuid>3bb27703-3df4-46fc-a21b-52d727f60f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[4]/a</value>
      <webElementGuid>cbc17f8a-5d10-4aa8-8860-6af11e728e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product-category/selenium/' and (text() = 'selenium' or . = 'selenium')]</value>
      <webElementGuid>4b34d68e-3de7-412b-b81c-69fcc07cea92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
