<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ThinkingInHTML</name>
   <tag></tag>
   <elementGuidId>f1ab61e3-2b3f-403e-a893-bb8464baf92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.post-163.product.type-product.status-publish.product_cat-html.product_tag-html.has-post-title.no-post-date.has-post-category.has-post-tag.has-post-comment.has-post-author.last.instock.sale.downloadable.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link > img.attachment-shop_catalog.size-shop_catalog.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li[8]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1045dad-74df-4667-b3bf-113cb88389be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>88ff731b-04f4-43fe-b980-45c8e3412f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d9b40d4c-ed1d-422c-bac6-72656aa879ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-300x300.jpg</value>
      <webElementGuid>d52b68d4-10ad-4c4a-ac31-00f70bf19285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_catalog size-shop_catalog wp-post-image</value>
      <webElementGuid>8924f3a2-ee4e-4440-bbe1-515afe9d2f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Thinking in HTML</value>
      <webElementGuid>24365f87-9ad3-4025-9dea-f12c7cdfbb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>72f1a8e9-14be-4b60-afc5-05a09dba9e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>da3076f9-26d7-4012-932c-4ff8f05b9c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thinking in HTML</value>
      <webElementGuid>17e37cf3-f913-440d-a6fc-665c56fbacd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-300x300.jpg 300w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-600x600.jpg 600w</value>
      <webElementGuid>0993a611-27d8-4ed0-b0e0-f2d057381794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>760a1a03-f6c4-4acf-bec2-609bf75f056b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[@class=&quot;products masonry-done&quot;]/li[@class=&quot;post-163 product type-product status-publish product_cat-html product_tag-html has-post-title no-post-date has-post-category has-post-tag has-post-comment has-post-author last instock sale downloadable taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link&quot;]/img[@class=&quot;attachment-shop_catalog size-shop_catalog wp-post-image&quot;]</value>
      <webElementGuid>2434cba5-7a5a-449c-939a-6fbee23640b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[8]/a/img</value>
      <webElementGuid>47b8835f-1945-48fd-8e76-6e25041b87cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Thinking in HTML']</value>
      <webElementGuid>4c839ac3-f798-400a-9bc0-d3eb0ded552e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/img</value>
      <webElementGuid>4e7b3f79-4383-4983-b2a1-79e666bd4394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Thinking-in-HTML-300x300.jpg' and @alt = 'Thinking in HTML' and @title = 'Thinking in HTML']</value>
      <webElementGuid>3c3c5637-b52d-42b3-a2e4-3ae337042ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
