<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FunctionalProgrammingJS</name>
   <tag></tag>
   <elementGuidId>9239d7f3-dfea-4f9d-9ef0-b938ee894756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.post-170.product.type-product.status-publish.product_cat-javascript.product_tag-javascript.has-post-title.no-post-date.has-post-category.has-post-tag.has-post-comment.has-post-author.instock.downloadable.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link > img.attachment-shop_catalog.size-shop_catalog.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b4024d4-f4ba-4d08-b453-1963425bed4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>e5e6d7d1-9223-4fb2-b514-e281d0aff729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b22e5415-68eb-43ce-8670-eb38a20ef9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-300x300.jpg</value>
      <webElementGuid>3fe5df8f-b255-4304-8d98-106e49fca55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_catalog size-shop_catalog wp-post-image</value>
      <webElementGuid>fcad09e3-424d-4d1e-9190-35521456b9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Functional Programming in JS</value>
      <webElementGuid>d3534be1-d996-4b81-97de-e5746ad1e76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c1034d1b-123b-47d5-9c8f-d0cb132a144c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5f5d291f-1914-4231-a5a3-92b3ed5a8736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Functional Programming in JS</value>
      <webElementGuid>f9092462-e2ff-4575-874f-0d8e26e0b661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-300x300.jpg 300w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-600x600.jpg 600w</value>
      <webElementGuid>402a3dd4-71f1-4241-8ac1-22eeac7359b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>474eb0f9-e3e2-43ca-a59f-0a0ae6e0a0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[@class=&quot;products masonry-done&quot;]/li[@class=&quot;post-170 product type-product status-publish product_cat-javascript product_tag-javascript has-post-title no-post-date has-post-category has-post-tag has-post-comment has-post-author  instock downloadable taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link&quot;]/img[@class=&quot;attachment-shop_catalog size-shop_catalog wp-post-image&quot;]</value>
      <webElementGuid>d20a0638-d8be-4f96-816e-2313abe776a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[2]/a/img</value>
      <webElementGuid>55523a72-5a2f-4fc6-bff8-ec06382dc6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Functional Programming in JS']</value>
      <webElementGuid>b9af9908-9c65-4ae1-8f2d-c5c75b3ad99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>d2980692-07a3-4187-b779-8ed9b36556de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Functional-Programming-in-JS-300x300.jpg' and @alt = 'Functional Programming in JS' and @title = 'Functional Programming in JS']</value>
      <webElementGuid>cd37ce9b-8048-48aa-940b-bd80639302f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
