<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_JSDataStructure</name>
   <tag></tag>
   <elementGuidId>547c4ccf-a07b-48b9-8a9d-fa0ac61e1b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.post-180.product.type-product.status-publish.product_cat-javascript.product_tag-javascript.has-post-title.no-post-date.has-post-category.has-post-tag.has-post-comment.has-post-author.first.instock.downloadable.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link > img.attachment-shop_catalog.size-shop_catalog.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li[5]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9fc32662-efca-4255-b1ad-02056dd452af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>e79149f8-70bc-4203-bf8c-d18f7fa717ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>9e2a52c3-20bc-4c9d-b057-fd92a47fc9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-300x300.jpg</value>
      <webElementGuid>3569d2b9-939f-4560-b4ce-b9f97d3f2da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_catalog size-shop_catalog wp-post-image</value>
      <webElementGuid>4d5b6cae-63ba-4e59-830d-646b983c40de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Learning JavaScript Data Structures and Algorith</value>
      <webElementGuid>ebdcf230-13c5-40f1-8c4b-f282e493d854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4271898f-5aeb-4791-9f1e-898172fd0a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>83e779b1-b3e9-49af-8e89-0896f547446b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Learning JavaScript Data Structures and Algorith</value>
      <webElementGuid>8ad77f26-67f2-4f02-ab18-e578d8756cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-300x300.jpg 300w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-600x600.jpg 600w</value>
      <webElementGuid>50a18281-6e87-4ff0-a521-9457c7f165c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>23b4c56d-7af9-4ffc-b405-fd87e9613cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[@class=&quot;products masonry-done&quot;]/li[@class=&quot;post-180 product type-product status-publish product_cat-javascript product_tag-javascript has-post-title no-post-date has-post-category has-post-tag has-post-comment has-post-author first instock downloadable taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link&quot;]/img[@class=&quot;attachment-shop_catalog size-shop_catalog wp-post-image&quot;]</value>
      <webElementGuid>d0e5f584-c602-4ec8-aacf-ca30a643675c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[5]/a/img</value>
      <webElementGuid>91b0bd83-ae61-4807-8558-ce6b70477978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Learning JavaScript Data Structures and Algorith']</value>
      <webElementGuid>ebc65831-a3f0-4624-ad62-3728ebc3c947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/img</value>
      <webElementGuid>85e428d7-e01d-4e43-9f43-a2183820d611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Learning-JavaScript-Data-Structures-and-Algorith-300x300.jpg' and @alt = 'Learning JavaScript Data Structures and Algorith' and @title = 'Learning JavaScript Data Structures and Algorith']</value>
      <webElementGuid>aa06ab2f-cfa7-4152-b382-3fe5dc45c666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
