<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResult_AndroidQuickStartGuide</name>
   <tag></tag>
   <elementGuidId>6f570edc-ea85-4aa1-9aa2-9505d41c76ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Android Quick Start Guide&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-169']/div/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>56a98083-5a96-4fe8-accc-94d6dcc4fe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product/android-quick-start-guide/</value>
      <webElementGuid>0867a4b8-04c8-44ac-8535-3b5f992622e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Android Quick Start Guide</value>
      <webElementGuid>1975b6c2-7519-42f7-8c4e-456022c6c1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Android Quick Start Guide</value>
      <webElementGuid>3403d1fb-b838-43c5-a15f-ae86b8b155e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-169&quot;)/div[@class=&quot;post-content&quot;]/div[@class=&quot;post-content-inner&quot;]/h2[@class=&quot;post-title entry-title&quot;]/a[1]</value>
      <webElementGuid>7ea477c3-9742-4f91-b2a8-ee18441b2d5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-169']/div/div/h2/a</value>
      <webElementGuid>7dc51fa8-2bbd-402e-9e56-fa8eea97b3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Android Quick Start Guide')]</value>
      <webElementGuid>90a041d4-856b-411a-a0fe-59b752348a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='android'])[1]/following::a[2]</value>
      <webElementGuid>8bb8babf-e62c-40b6-8686-12b8262816dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::a[1]</value>
      <webElementGuid>761da626-6afd-49dc-a107-374e7f45ffe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refine By >'])[1]/preceding::a[3]</value>
      <webElementGuid>5be6cad7-4813-45cf-b982-c50d1fcf1f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Android Quick Start Guide']/parent::*</value>
      <webElementGuid>3eff1e6d-773b-426c-a775-c6093491abef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://practice.automationtesting.in/product/android-quick-start-guide/')])[2]</value>
      <webElementGuid>6d32f199-0e55-4819-9bee-ddf91594741e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>1342a5dd-666d-49cc-9017-bbc4ee48e0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product/android-quick-start-guide/' and @title = 'Android Quick Start Guide' and (text() = 'Android Quick Start Guide' or . = 'Android Quick Start Guide')]</value>
      <webElementGuid>803fef3b-6021-4460-bdf3-482ba14b8d84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
