<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResult_JSDataStructures</name>
   <tag></tag>
   <elementGuidId>e7e93661-8022-4251-9f95-544bdc9fcde9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;JS Data Structures and Algorithm&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-180']/div/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57fded5e-d8f2-4a72-9072-54846787f6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product/learning-javascript-data-structures-and-algorithm/</value>
      <webElementGuid>3412c856-57f4-4677-97ed-5db86eeecb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>JS Data Structures and Algorithm</value>
      <webElementGuid>9fc8aa18-e758-4734-b252-11b489574fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JS Data Structures and Algorithm</value>
      <webElementGuid>85b21f60-27d7-4ad3-9811-293d21f9d7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-180&quot;)/div[@class=&quot;post-content&quot;]/div[@class=&quot;post-content-inner&quot;]/h2[@class=&quot;post-title entry-title&quot;]/a[1]</value>
      <webElementGuid>1eed1f96-1183-4734-b93f-b131f970824b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-180']/div/div/h2/a</value>
      <webElementGuid>e00e2cde-1bdf-4ec8-8522-22a0b698e853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JS Data Structures and Algorithm')]</value>
      <webElementGuid>d113508e-bb10-45a5-9fba-6adac13c4968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/following::a[3]</value>
      <webElementGuid>47ca638c-8937-4f5d-a14e-2c66efdccb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mastering JavaScript'])[1]/following::a[4]</value>
      <webElementGuid>7158b1af-dc92-4ab9-ba52-34935e626da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[2]/preceding::a[1]</value>
      <webElementGuid>5108ea32-4596-49d1-90dd-48ac9f1bf2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Programming in JS'])[1]/preceding::a[4]</value>
      <webElementGuid>82c6f891-6045-4d7e-a087-fdec02a30e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JS Data Structures and Algorithm']/parent::*</value>
      <webElementGuid>b0a94d73-90d4-4038-aafd-b6bed9f71749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://practice.automationtesting.in/product/learning-javascript-data-structures-and-algorithm/')])[2]</value>
      <webElementGuid>9c972a4e-5a38-458a-98d1-07f374d4befa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/div/div/h2/a</value>
      <webElementGuid>7915852f-fc82-4159-9946-7250625201f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product/learning-javascript-data-structures-and-algorithm/' and @title = 'JS Data Structures and Algorithm' and (text() = 'JS Data Structures and Algorithm' or . = 'JS Data Structures and Algorithm')]</value>
      <webElementGuid>c23b046e-5e89-4092-84df-e354c070c03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
