<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResult_MasteringJavaScript</name>
   <tag></tag>
   <elementGuidId>17097ab9-8ab3-41d8-8993-76150e6af5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Mastering JavaScript&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-165']/div/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d0669e84-a2f0-4f01-b833-f3699cb08772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product/mastering-javascript/</value>
      <webElementGuid>5bfdec2a-6c72-419c-9023-d3d88260a16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mastering JavaScript</value>
      <webElementGuid>d2189cb5-720c-4576-b570-c371a11752d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mastering JavaScript</value>
      <webElementGuid>45878f91-a588-4728-9fff-211b74dc1e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-165&quot;)/div[@class=&quot;post-content&quot;]/div[@class=&quot;post-content-inner&quot;]/h2[@class=&quot;post-title entry-title&quot;]/a[1]</value>
      <webElementGuid>65be242f-cfe1-474c-b6b2-2d9dc287fd53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-165']/div/div/h2/a</value>
      <webElementGuid>d7c4c044-e9dc-40eb-93dc-6f938cc67220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mastering JavaScript')]</value>
      <webElementGuid>2973363d-431c-4d52-a31a-9bbb49945eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='java'])[1]/following::a[2]</value>
      <webElementGuid>96464faf-0db1-45eb-b873-28f0ade7214d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::a[1]</value>
      <webElementGuid>7647359e-eb56-4586-a455-3a3a7fa6eed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS Data Structures and Algorithm'])[1]/preceding::a[4]</value>
      <webElementGuid>11f17cb9-b01c-43d1-b898-ee20463853c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mastering JavaScript']/parent::*</value>
      <webElementGuid>3cd7e4ef-c519-4d56-ae2e-775fe0a552f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://practice.automationtesting.in/product/mastering-javascript/')])[2]</value>
      <webElementGuid>0f83c44e-ae93-4270-b9eb-3d658fab1458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>f58e201a-2731-40d1-beb8-7c8a0355985a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product/mastering-javascript/' and @title = 'Mastering JavaScript' and (text() = 'Mastering JavaScript' or . = 'Mastering JavaScript')]</value>
      <webElementGuid>27b999d2-57bc-41f9-99c5-098e7cd31f43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
