<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResult_FunctionalProgramming</name>
   <tag></tag>
   <elementGuidId>2f2e7912-da63-45a5-ba6b-76b3212c9029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Functional Programming in JS&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-170']/div/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fae3f9e3-ec3e-4563-b0ed-11173920fbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product/functional-programming-in-js/</value>
      <webElementGuid>472b8647-b06b-460c-8f31-d783b5229214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Functional Programming in JS</value>
      <webElementGuid>d4295445-2029-41cb-9875-91917f1bca25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Functional Programming in JS</value>
      <webElementGuid>dc13d776-be8a-44ce-bbd8-fdba1dcf83d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-170&quot;)/div[@class=&quot;post-content&quot;]/div[@class=&quot;post-content-inner&quot;]/h2[@class=&quot;post-title entry-title&quot;]/a[1]</value>
      <webElementGuid>d93007c1-a4e0-46d6-9a77-0648b3da3c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-170']/div/div/h2/a</value>
      <webElementGuid>fe1aefd5-b405-4025-a96b-5545d2626476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Functional Programming in JS')]</value>
      <webElementGuid>6cf25ddb-18d8-4241-9f36-2d06bcc0cdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[2]/following::a[3]</value>
      <webElementGuid>3de30117-3d0d-4df1-9dd4-afc449fe1d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS Data Structures and Algorithm'])[1]/following::a[4]</value>
      <webElementGuid>55cf70f1-33b9-4ddc-aadb-7ec8002f347b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[3]/preceding::a[1]</value>
      <webElementGuid>698a6346-4e08-4f60-9b70-b3be474df0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refine By >'])[1]/preceding::a[3]</value>
      <webElementGuid>1e9b319d-0323-4a18-a30a-3a9d9734ef6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Functional Programming in JS']/parent::*</value>
      <webElementGuid>ae06b51e-89b4-4135-a232-717e7686c36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://practice.automationtesting.in/product/functional-programming-in-js/')])[2]</value>
      <webElementGuid>9fdaf483-acec-48e8-aa69-2f2ff9c4306d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/div/div/h2/a</value>
      <webElementGuid>82472c3d-3310-4995-89b6-f43a71e2bc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product/functional-programming-in-js/' and @title = 'Functional Programming in JS' and (text() = 'Functional Programming in JS' or . = 'Functional Programming in JS')]</value>
      <webElementGuid>6d9c84ae-ed26-469c-86cd-d685ecccca27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
