<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_price600.00</name>
   <tag></tag>
   <elementGuidId>b728ee75-84a5-4e13-9110-e49fb852974d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.woocommerce-Price-amount.amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li/a/span[2]/del/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29cb8fae-db2f-4ff3-b3a0-0c80a266b831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-Price-amount amount</value>
      <webElementGuid>8a0488d8-292f-4351-b667-463c55debe27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹600.00</value>
      <webElementGuid>8d82a96a-3730-4e09-9de1-a394e1e5e60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[@class=&quot;products masonry-done&quot;]/li[@class=&quot;post-169 product type-product status-publish product_cat-android product_tag-android has-post-title no-post-date has-post-category has-post-tag has-post-comment has-post-author first instock sale downloadable taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link&quot;]/span[@class=&quot;price&quot;]/del[1]/span[@class=&quot;woocommerce-Price-amount amount&quot;]</value>
      <webElementGuid>9ab1491e-56e4-49db-b6af-a853e2663646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li/a/span[2]/del/span</value>
      <webElementGuid>0147541e-62ec-46cc-b8fb-78d3cd6da338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android Quick Start Guide'])[1]/following::span[2]</value>
      <webElementGuid>73792c7d-5567-4e8c-9ec9-fe041f1c4cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[1]/following::span[2]</value>
      <webElementGuid>07e0733e-1978-4791-aab8-2dd4f3f32137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[2]/preceding::span[2]</value>
      <webElementGuid>5628a852-1ad5-4058-aec7-a2630eb7df20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='600.00']/parent::*</value>
      <webElementGuid>3cf3044a-bdf3-4625-b63a-68ec6a02d654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//del/span</value>
      <webElementGuid>e9c177fb-fbc6-4cbd-887e-abe8fab71e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '₹600.00' or . = '₹600.00')]</value>
      <webElementGuid>2a2a233d-8840-4cf7-bf5e-d2dccc28655d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
