<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_RefineBy</name>
   <tag></tag>
   <elementGuidId>ebdb2ef5-db42-4442-9f20-f1ca72f25f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.widgettitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text-3']/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>73c2e05a-c0a2-4e6d-8981-d622ba057c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widgettitle</value>
      <webElementGuid>2bcaadc7-de11-468c-897b-cc04c39133dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refine By ></value>
      <webElementGuid>aeefc324-08aa-4708-8102-3c32bfa144dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-3&quot;)/h4[@class=&quot;widgettitle&quot;]</value>
      <webElementGuid>47c804dc-d270-43d8-b7cd-0c24194d92e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text-3']/h4</value>
      <webElementGuid>dc677851-8378-4571-8a8e-4690f4263c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to basket'])[8]/following::h4[1]</value>
      <webElementGuid>6d248e32-bb1a-440e-a799-28e3bb2b5ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[10]/following::h4[1]</value>
      <webElementGuid>992731f0-de5f-4a23-a74f-39412f5b4d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by price'])[1]/preceding::h4[1]</value>
      <webElementGuid>06ac3a58-7536-4d61-94a4-aa8237cea334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::h4[2]</value>
      <webElementGuid>eca2eedc-da4c-4f28-b6d3-69bf8c5aea36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refine By >']/parent::*</value>
      <webElementGuid>201b9bef-e7c6-4347-a053-1c84e7e974d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>a9fc5c82-7a32-4126-a181-5b9f6c696889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Refine By >' or . = 'Refine By >')]</value>
      <webElementGuid>fddd7924-e800-4a21-917e-7eae3c030745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
