<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Undo</name>
   <tag></tag>
   <elementGuidId>14397fc5-ddef-403c-8a41-4d1a282c5bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[text()='Undo?']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-message > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fccfc5be-a77f-4647-a7cf-8e67e60aba81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/basket/?undo_item=3636638817772e42b59d74cff571fbb3&amp;_wpnonce=c3349228a8</value>
      <webElementGuid>1a4e99bb-01a5-4dde-91c2-585ea7b257dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Undo?</value>
      <webElementGuid>fb00fad8-3ee4-4b8d-bedc-b71e745b5aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-34&quot;)/div[@class=&quot;page-content entry-content&quot;]/div[@class=&quot;woocommerce-message&quot;]/a[1]</value>
      <webElementGuid>75679353-6e9c-4440-ab49-36bc5c6c4965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-34']/div/div/a</value>
      <webElementGuid>e8ac4a0e-b89e-47a4-afc4-b8d7ec0be8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Undo?')]</value>
      <webElementGuid>8bfe2fbc-cc1a-4d22-8554-257bf1fd2260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹0.00'])[1]/following::a[3]</value>
      <webElementGuid>76d33b1b-f962-457c-9cbc-953e3c5f0030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return To Shop'])[1]/preceding::a[1]</value>
      <webElementGuid>cf840c8d-f7ee-4237-8d4b-2b850966941e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe Here'])[1]/preceding::a[8]</value>
      <webElementGuid>cf03e497-4907-41ac-8b65-aa118543b887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Undo?']/parent::*</value>
      <webElementGuid>e84a3df9-a0b8-49d8-a4de-d70a78da23c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/basket/?undo_item=3636638817772e42b59d74cff571fbb3&amp;_wpnonce=c3349228a8')]</value>
      <webElementGuid>28fdbefc-3e2a-4baa-9c3d-5315106df7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>c1efce6d-215c-4b03-a6ed-e3d78c6eca77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/basket/?undo_item=3636638817772e42b59d74cff571fbb3&amp;_wpnonce=c3349228a8' and (text() = 'Undo?' or . = 'Undo?')]</value>
      <webElementGuid>25f3e073-cb3b-4f49-a9d3-9459f946d1d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
