<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>price_450.00</name>
   <tag></tag>
   <elementGuidId>60eec580-cd1a-4494-a1bd-175c3ab6e67a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-34']/div/div/form/table/tbody/tr/td[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.woocommerce-Price-amount.amount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84b8c938-bc14-498f-85d4-8231cd7ec50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-Price-amount amount</value>
      <webElementGuid>fc2293a0-2928-48c8-ab96-e2c5e20b1506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹450.00</value>
      <webElementGuid>1ec07e26-1581-4610-911a-459b221ce4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-34&quot;)/div[@class=&quot;page-content entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[1]/table[@class=&quot;shop_table shop_table_responsive cart&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-price&quot;]/span[@class=&quot;woocommerce-Price-amount amount&quot;]</value>
      <webElementGuid>2d74cf3a-5b6d-49af-b512-542611270e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-34']/div/div/form/table/tbody/tr/td[4]/span</value>
      <webElementGuid>01adfd4a-f90c-428b-a6fb-8e706ef2a497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android Quick Start Guide'])[1]/following::span[1]</value>
      <webElementGuid>fe711aec-8eb0-40fd-826b-df9ef053c28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::span[1]</value>
      <webElementGuid>3786dc02-5ccf-4376-beb2-4b28b50e14bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[2]/preceding::span[2]</value>
      <webElementGuid>cd562fbb-d13f-486b-85c6-cdab65da399b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='450.00']/parent::*</value>
      <webElementGuid>0b5a7ab1-055f-44bf-83eb-e98610dd3103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span</value>
      <webElementGuid>4265f838-6721-4772-8dfe-68718d04c72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '₹450.00' or . = '₹450.00')]</value>
      <webElementGuid>9644a8bd-f29d-4322-b75c-ddeea056657f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
