<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>remove_HTML5Forms</name>
   <tag></tag>
   <elementGuidId>17f8d78b-119f-48a1-9591-d3d406caa19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[.//a[contains(text(),'HTML5 Forms')]]//a[contains(@class,'remove')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edce2b11-08d5-4612-b65a-21a387aa0692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/basket/?remove_item=fc221309746013ac554571fbd180e1c8&amp;_wpnonce=e3e9241344</value>
      <webElementGuid>010efea9-64ab-452c-aafe-db109326b8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove</value>
      <webElementGuid>db7f0a80-6721-4d21-8491-855bb76a0f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove this item</value>
      <webElementGuid>6e39d082-f9c4-4f35-8ad8-f64dd099fc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>181</value>
      <webElementGuid>c5c88cae-b552-4c4a-b2e5-74be89ba1632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>b9d552dd-2600-4e6a-ae84-fe1673ad57d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-34&quot;)/div[@class=&quot;page-content entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[1]/table[@class=&quot;shop_table shop_table_responsive cart&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-remove&quot;]/a[@class=&quot;remove&quot;]</value>
      <webElementGuid>621ef389-abb0-44b9-bacb-8e69d618343f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-34']/div/div/form/table/tbody/tr[3]/td/a</value>
      <webElementGuid>e2ee1e2c-f858-40d1-a767-efadb23ad68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'×')])[3]</value>
      <webElementGuid>46ce6490-6911-402c-ab38-1fe28a6c85ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[4]/following::a[1]</value>
      <webElementGuid>4425438f-4c68-44c3-8069-1a3894e31713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[3]/following::a[1]</value>
      <webElementGuid>265d3d89-0b78-4433-9d78-bd1440d4d41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML5 Forms'])[1]/preceding::a[2]</value>
      <webElementGuid>944cb7e9-1e85-49b0-8cb5-aff97243bdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[5]/preceding::a[3]</value>
      <webElementGuid>762815de-2159-4825-9eb4-41fc59d62444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/basket/?remove_item=fc221309746013ac554571fbd180e1c8&amp;_wpnonce=e3e9241344')]</value>
      <webElementGuid>3536723b-eafc-4ec8-91cd-056fc10f2e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>d652d1fe-207a-4ff1-9f61-acb99e06149d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/basket/?remove_item=fc221309746013ac554571fbd180e1c8&amp;_wpnonce=e3e9241344' and @title = 'Remove this item' and (text() = '×' or . = '×')]</value>
      <webElementGuid>6ab20755-3e63-48ae-a91e-3406d4803319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
