<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>remove_MasteringJavaScript</name>
   <tag></tag>
   <elementGuidId>b7e1ec3d-2200-4ebc-b979-48f3ca28ad79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[.//a[contains(text(),'Mastering JavaScript')]]//a[contains(@class,'remove')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ba6702d-eb9f-4cd8-92af-22d64d5e091a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/basket/?remove_item=9766527f2b5d3e95d4a733fcfb77bd7e&amp;_wpnonce=e3e9241344</value>
      <webElementGuid>a359fea8-d282-4e8e-914c-011a128791f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove</value>
      <webElementGuid>3a59946c-c524-478f-a65a-de46059d2daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove this item</value>
      <webElementGuid>9013a9c4-b4a5-4ca0-929a-f5f701522300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>165</value>
      <webElementGuid>030e0f22-70a6-4df6-a028-95086d8dd7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>8b160d36-469b-4bb3-9e7e-dd70a1ec423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-34&quot;)/div[@class=&quot;page-content entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[1]/table[@class=&quot;shop_table shop_table_responsive cart&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-remove&quot;]/a[@class=&quot;remove&quot;]</value>
      <webElementGuid>be6066ef-28bc-45dd-b93f-d8dc857f2f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-34']/div/div/form/table/tbody/tr[6]/td/a</value>
      <webElementGuid>c0851dfc-1c8e-4c63-9ce1-001bbc811af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'×')])[6]</value>
      <webElementGuid>bdc0e151-581d-4c3f-b379-898b5460c7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[10]/following::a[1]</value>
      <webElementGuid>f2ed0fac-d1f6-41ce-92cb-25a3c75dcaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[9]/following::a[1]</value>
      <webElementGuid>502fe435-dca7-4386-9ee4-7f84b3f3ed6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mastering JavaScript'])[1]/preceding::a[2]</value>
      <webElementGuid>68ce99da-47a3-47e7-a1ed-ca847049bf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[11]/preceding::a[3]</value>
      <webElementGuid>6e046719-4cb4-453f-9ebf-0938502f97ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/basket/?remove_item=9766527f2b5d3e95d4a733fcfb77bd7e&amp;_wpnonce=e3e9241344')]</value>
      <webElementGuid>49c5b4b7-457d-41a8-a2df-52e4fc0ff69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/a</value>
      <webElementGuid>44611f5c-ccae-477a-8897-54d3ee6bff28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/basket/?remove_item=9766527f2b5d3e95d4a733fcfb77bd7e&amp;_wpnonce=e3e9241344' and @title = 'Remove this item' and (text() = '×' or . = '×')]</value>
      <webElementGuid>8139d436-d372-4299-8d97-849be242f8e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
