<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>remove_JSDataStructures</name>
   <tag></tag>
   <elementGuidId>9b7517b1-b39f-4406-8c11-37bfdcdaeeda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[.//a[contains(text(),'JS Data Structures and Algorithm')]]//a[contains(@class,'remove')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c96934b-6871-4511-9629-a1739ec61aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/basket/?remove_item=045117b0e0a11a242b9765e79cbf113f&amp;_wpnonce=7b28a572a6</value>
      <webElementGuid>86aaf6fa-f884-4304-86a9-98d343da5499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove</value>
      <webElementGuid>f12393cd-fc7d-41b6-9eae-094f35a38788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove this item</value>
      <webElementGuid>27474270-9c1d-4b71-afc4-01c6094f1dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>180</value>
      <webElementGuid>25937516-1806-44be-8ece-a7687a5a677e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>76273441-2055-4416-ae88-52a02cf76d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-34&quot;)/div[@class=&quot;page-content entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[1]/table[@class=&quot;shop_table shop_table_responsive cart&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-remove&quot;]/a[@class=&quot;remove&quot;]</value>
      <webElementGuid>dbf0fa94-0d8b-410d-a888-97b29c8ed04b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-34']/div/div/form/table/tbody/tr[2]/td/a</value>
      <webElementGuid>97720b37-f106-4da1-9956-ad83cc279bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'×')])[2]</value>
      <webElementGuid>e0cadbb9-af0e-4d25-82f4-6494775ba4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[2]/following::a[1]</value>
      <webElementGuid>87b5f957-79df-4cc4-a9fb-c840af055777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[1]/following::a[1]</value>
      <webElementGuid>ac6eb1ca-679e-40b8-b365-a4ebc0a7618a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS Data Structures and Algorithm'])[1]/preceding::a[2]</value>
      <webElementGuid>8a26c6df-23d9-4a07-a03c-ab7386738be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[3]/preceding::a[3]</value>
      <webElementGuid>fae9a9d8-5601-4e5d-9dba-0903f9ea830a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/basket/?remove_item=045117b0e0a11a242b9765e79cbf113f&amp;_wpnonce=7b28a572a6')]</value>
      <webElementGuid>126a24d4-100b-4a9f-9117-c3b5bca7fa2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/a</value>
      <webElementGuid>96a666c6-ac1a-4a6e-bb53-938ce523059e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/basket/?remove_item=045117b0e0a11a242b9765e79cbf113f&amp;_wpnonce=7b28a572a6' and @title = 'Remove this item' and (text() = '×' or . = '×')]</value>
      <webElementGuid>3cfb75a1-efd1-4839-a385-b3c4307cfe86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
