<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Province</name>
   <tag></tag>
   <elementGuidId>0a73242b-e0e3-40ee-9565-f230d84b1864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_state_field']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_state_field > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a8b5bef2-9dc3-46a5-80e0-84c31c9326f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billing_state</value>
      <webElementGuid>7786893e-850c-4721-a4b9-73844e85283e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Province *</value>
      <webElementGuid>5f1fad77-85c3-447f-bc2e-62321a0a111c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_state_field&quot;)/label[1]</value>
      <webElementGuid>57ee83d0-40eb-42d8-92b4-951396932a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_state_field']/label</value>
      <webElementGuid>69e0af0e-678b-4f45-988f-3b354addddbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::label[1]</value>
      <webElementGuid>742dabfb-6ef5-42ed-bf5f-dbf9794de1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option…'])[1]/preceding::label[1]</value>
      <webElementGuid>229633cf-6ccc-4152-9964-00cd78f0763c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Province']/parent::*</value>
      <webElementGuid>fa665a8c-a1cb-40ce-a049-4fbcd917e42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/label</value>
      <webElementGuid>4694be20-2c27-425a-9216-53ba1ac14e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Province *' or . = 'Province *')]</value>
      <webElementGuid>909e5522-b3db-47ad-80cd-a3bbbbb76357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
