<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Last Name</name>
   <tag></tag>
   <elementGuidId>91d78cd6-2307-4fa5-b44a-191498d73aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_last_name_field']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_last_name_field > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cb51a300-9896-41f8-b63c-3cd1b7083085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>1b3911de-3774-47c2-896d-313df379db6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Name *</value>
      <webElementGuid>927a11aa-ffce-4eec-a513-0aadd448c4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_last_name_field&quot;)/label[1]</value>
      <webElementGuid>e4a19efb-43a3-4220-aa98-3027d1fed075</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_last_name_field']/label</value>
      <webElementGuid>ddcc4368-d7d8-4dee-8fda-1cf6b747c6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::label[1]</value>
      <webElementGuid>8d3e5b20-76d8-44c4-884c-7e86a26c4957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/preceding::label[1]</value>
      <webElementGuid>0f5e0477-bc38-41e8-bd5c-77bebc5cb6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last Name']/parent::*</value>
      <webElementGuid>0e0d924f-e3d5-4ff7-81d5-3766d2b1a82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p[2]/label</value>
      <webElementGuid>4642bb1c-3fb0-429f-95ee-82dd26f190dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Last Name *' or . = 'Last Name *')]</value>
      <webElementGuid>a9e7fefb-c3ae-4ec3-ac78-3a9d788d3bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
