<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_PaypalMethod</name>
   <tag></tag>
   <elementGuidId>cb077f66-c05d-4cde-b3a3-3155b9fb0825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_ppec_paypal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_method_ppec_paypal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bf06c00-9643-496a-93b6-1ca84206af15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_ppec_paypal</value>
      <webElementGuid>d9f3b3d6-32f0-4584-ba9e-5943ff2252d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a9cf52c7-e27b-4e5a-b266-e2c79f22e7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>016f6386-4173-4df6-9ee8-0a854193798c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>e7fd83c0-7982-4877-bd1b-6a6767d3a83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ppec_paypal</value>
      <webElementGuid>c81f5781-fb1d-426f-8ed5-9f584d9afac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-order_button_text</name>
      <type>Main</type>
      <value>Continue to payment</value>
      <webElementGuid>18b7fd71-dce0-4f34-aff8-a157afc861da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_ppec_paypal&quot;)</value>
      <webElementGuid>5f94944b-3a1c-4129-868a-a713c3902ccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_ppec_paypal']</value>
      <webElementGuid>8bfe80bc-65f3-433f-91e6-72d0333eade4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[4]/input</value>
      <webElementGuid>afad5fb4-63ee-4032-a507-59cd546d0b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/input</value>
      <webElementGuid>96c2ae37-26aa-42ed-ac20-ffee28599970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_ppec_paypal' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>064238d2-e808-4a69-b54b-6b97e9daf395</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
