<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Total</name>
   <tag></tag>
   <elementGuidId>19cc021a-02f7-4243-ac81-91674f85acaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-35']/div/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a1ad1127-6686-4608-8a38-73e12ef95a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>eaef78bd-a8c3-4c4b-86d4-9f163888a423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Total:				₹459.00
			</value>
      <webElementGuid>2db8ac3d-4858-4306-9810-0023a196898a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-35&quot;)/div[@class=&quot;page-content entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/ul[@class=&quot;woocommerce-thankyou-order-details order_details&quot;]/li[@class=&quot;total&quot;]</value>
      <webElementGuid>d3b8e8f9-8211-4e5d-bee1-7a44bff6f723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-35']/div/div/ul/li[3]</value>
      <webElementGuid>3393e31c-08aa-4ac2-abbd-ee6e1153e994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='April 9, 2026'])[1]/following::li[1]</value>
      <webElementGuid>bbc98b50-cc66-4476-bb62-6cdc6631cf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total:']/parent::*</value>
      <webElementGuid>0303de83-9760-418e-a199-5cb3c619e2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>98a69485-ae19-4cf4-baee-2774aed0448e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
				Total:				₹459.00
			' or . = '
				Total:				₹459.00
			')]</value>
      <webElementGuid>aee7f586-c468-4b8a-b0cb-f6327e4175c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
