<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_PleaseSendAcheque</name>
   <tag></tag>
   <elementGuidId>3d678cd6-1423-4fa3-b871-62544868f8cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-35']/div/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>75219f18-f190-4558-b04a-d4836fbdf4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please send a cheque to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</value>
      <webElementGuid>5247f6c0-ffb0-4f8f-83a1-b6b01ee308ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-35&quot;)/div[@class=&quot;page-content entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/p[2]</value>
      <webElementGuid>fc290f54-3e47-4b37-9f46-5a7c2c995e11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-35']/div/div/p[2]</value>
      <webElementGuid>f73b91b6-0650-4940-bebd-8d271034a4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Payments'])[1]/following::p[1]</value>
      <webElementGuid>fda40b43-743f-4548-b794-fbe30e685695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Details'])[1]/preceding::p[1]</value>
      <webElementGuid>97642ba7-a26f-490d-90e7-4c0219215e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/preceding::p[1]</value>
      <webElementGuid>9cf27157-56b5-4d5c-b08b-d67e51f2ab9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please send a cheque to Store Name, Store Street, Store Town, Store State / County, Store Postcode.']/parent::*</value>
      <webElementGuid>2986f04f-95af-4d9d-9167-776f36426b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>8d456e12-b742-4ae3-a518-b12a2763b7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Please send a cheque to Store Name, Store Street, Store Town, Store State / County, Store Postcode.' or . = 'Please send a cheque to Store Name, Store Street, Store Town, Store State / County, Store Postcode.')]</value>
      <webElementGuid>91ad32f0-5c71-490c-bd40-e37830c672e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
