<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_YourOrder</name>
   <tag></tag>
   <elementGuidId>58d83e8f-33dc-46e4-92da-6cb589b88502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='order_review_heading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_review_heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>5ee107b4-7fd4-4a8b-8fd4-8e19c0a7658f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_review_heading</value>
      <webElementGuid>b18e89f0-9279-4080-a8ba-a6b26a4d65b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your order</value>
      <webElementGuid>825a0bb8-7020-4cb9-a9d9-e259984bd271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_review_heading&quot;)</value>
      <webElementGuid>82cf3a4f-7fec-4cc6-9f5f-da6fd02f9f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='order_review_heading']</value>
      <webElementGuid>89a7da50-10a8-4c6a-9857-8df0c631f37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-35']/div/div/form[3]/h3</value>
      <webElementGuid>654e1a16-d4bb-4d71-81b3-b38ea764fe40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Notes'])[1]/following::h3[1]</value>
      <webElementGuid>4956f007-75ea-457f-90e0-5feb9b7a85aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Information'])[1]/following::h3[1]</value>
      <webElementGuid>29dda65c-4131-4625-af45-a3d5d6aa9800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/preceding::h3[1]</value>
      <webElementGuid>cbb1f81a-0779-4e26-a083-113e21adaa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::h3[1]</value>
      <webElementGuid>1479aedd-ea15-449b-8d05-e483663c7286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your order']/parent::*</value>
      <webElementGuid>22e090e2-61fb-4d67-bc8a-296918cbc693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/h3</value>
      <webElementGuid>982cd96c-a171-4b1b-bdd5-467af6695adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'order_review_heading' and (text() = 'Your order' or . = 'Your order')]</value>
      <webElementGuid>ffe97bdc-e11b-494a-9d12-0f41c2426777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
